# Sysbuild overrides for UF2-only builds.
SB_CONFIG_BOOTLOADER_NONE=y
SB_CONFIG_DFU_MULTI_IMAGE_PACKAGE_BUILD=n
SB_CONFIG_DFU_MULTI_IMAGE_PACKAGE_APP=n
SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=n
SB_CONFIG_MATTER_FACTORY_DATA_GENERATE=n
